name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    environment: K8S-SECRETS
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo yum install -y git
            git clone https://github.com/ElizaAugusta4/api-accounts-service.git
            cd api-accounts-service
            chmod +x ./deploy_k8s.sh
            ./deploy_k8s.sh